In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees,departments,on = "DeptID") #INNER JOIN

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [7]:
pd.merge(employees,departments,on = "DeptID",how = "left") #left JOIN

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [8]:
pd.merge(employees,departments,on = "DeptID",how = "right") #right JOIN

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [10]:
pd.merge(employees,departments,on = "DeptID",how = "outer") # outer JOIN

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [11]:
df1 = pd.DataFrame({"Name":["Alice","Bob"]})
df2 = pd.DataFrame({"Name":["Charlie","David"]})

In [12]:
df1

    Name
0  Alice
1    Bob

In [13]:
df2

      Name
0  Charlie
1    David

In [14]:
pd.concat([df1,df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [15]:
pd.concat([df1,df2],axis = 1)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [17]:
df1 = pd.DataFrame({"Name":["Alice","Bob"],"score":[432,456]})
df2 = pd.DataFrame({"Name":["Charlie","David"],"age":[23,23]})

In [19]:
df1

    Name  score
0  Alice    432
1    Bob    456

In [20]:
df2

      Name  age
0  Charlie   23
1    David   23

In [21]:
pd.concat([df1,df2])

      Name  score   age
0    Alice  432.0   NaN
1      Bob  456.0   NaN
0  Charlie    NaN  23.0
1    David    NaN  23.0

In [22]:
pd.concat([df1,df2],axis = 1)

    Name  score     Name  age
0  Alice    432  Charlie   23
1    Bob    456    David   23