In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("products.csv")

In [3]:
df

   product_id         product_name     category  price  stock
0        P101       Wireless Mouse  Electronics   1200     50
1        P102  Mechanical Keyboard  Electronics   3500     30
2        P103         Laptop Stand  Accessories   1800     40
3        P104         Office Chair    Furniture   7000     15
4        P105         Water Bottle  Accessories    600    100
5        P106      Monitor 24 inch  Electronics  12000     20
6        P107          Study Table    Furniture   9500     10
7        P108            USB Cable  Electronics    300    200
8        P109             Notebook   Stationery     80    500
9        P110              Pen Set   Stationery    250    150
10       P111    Bluetooth Speaker  Electronics   4500     25
11       P112            Desk Lamp    Furniture   2200     35
12       P113           Headphones  Electronics   2800     45
13       P114             Backpack  Accessories   1500     60
14       P115          Smart Watch  Electronics   8000     18
15       P116               Webcam  Electronics   2200     40
16       P117         Gaming Chair    Furniture  15000      8
17       P118           Power Bank  Electronics   1800     75
18       P119           Marker Set   Stationery    400    120
19       P120           Coffee Mug  Accessories    350     90
20       P121               LED TV    Furniture  30000     12
21       P122              Printer  Electronics   8500     14
22       P123         Tablet Stand  Accessories    900     55
23       P124                Diary   Stationery    150    300
24       P125         External HDD  Electronics   6500     22

In [4]:
df=df[df['price']>2000]

In [5]:
df

   product_id         product_name     category  price  stock
1        P102  Mechanical Keyboard  Electronics   3500     30
3        P104         Office Chair    Furniture   7000     15
5        P106      Monitor 24 inch  Electronics  12000     20
6        P107          Study Table    Furniture   9500     10
10       P111    Bluetooth Speaker  Electronics   4500     25
11       P112            Desk Lamp    Furniture   2200     35
12       P113           Headphones  Electronics   2800     45
14       P115          Smart Watch  Electronics   8000     18
15       P116               Webcam  Electronics   2200     40
16       P117         Gaming Chair    Furniture  15000      8
20       P121               LED TV    Furniture  30000     12
21       P122              Printer  Electronics   8500     14
24       P125         External HDD  Electronics   6500     22

In [6]:
df.to_csv("data_updates.csv")

In [7]:
df.to_csv("data_updated.csv",index = False)