In [1]:
import pandas as pd

In [2]:
data = [['harry',34],["jack",67],["jacob",67],["jacky",66]]

In [3]:
data

[['harry', 34], ['jack', 67], ['jacob', 67], ['jacky', 66]]

In [4]:
pd.DataFrame(data,columns=["Name","Marks"])

    Name  Marks
0  harry     34
1   jack     67
2  jacob     67
3  jacky     66

In [5]:
data = {"a":[4,6,3],"b":[56,54,343]}

In [6]:
data

{'a': [4, 6, 3], 'b': [56, 54, 343]}

In [7]:
df = pd.DataFrame(data)

In [8]:
df

   a    b
0  4   56
1  6   54
2  3  343

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2],[5,6]])

In [13]:
df = pd.DataFrame(arr,columns = ["a","b"])

In [14]:
df

   a  b
0  1  2
1  5  6

In [21]:
#df = pd.read_excel("file name.xlsx") reading xl file
#df = pd.read_jason("file name.jason") reading jason file
#df = pd.read_csv("https://www.kaggle.com/datasets/uciml/iris")  reading through url btw url is wrong here
df = pd.read_csv("products.csv")

In [22]:
df

   product_id         product_name     category  price  stock
0        P101       Wireless Mouse  Electronics   1200     50
1        P102  Mechanical Keyboard  Electronics   3500     30
2        P103         Laptop Stand  Accessories   1800     40
3        P104         Office Chair    Furniture   7000     15
4        P105         Water Bottle  Accessories    600    100
5        P106      Monitor 24 inch  Electronics  12000     20
6        P107          Study Table    Furniture   9500     10
7        P108            USB Cable  Electronics    300    200
8        P109             Notebook   Stationery     80    500
9        P110              Pen Set   Stationery    250    150
10       P111    Bluetooth Speaker  Electronics   4500     25
11       P112            Desk Lamp    Furniture   2200     35
12       P113           Headphones  Electronics   2800     45
13       P114             Backpack  Accessories   1500     60
14       P115          Smart Watch  Electronics   8000     18
15       P116               Webcam  Electronics   2200     40
16       P117         Gaming Chair    Furniture  15000      8
17       P118           Power Bank  Electronics   1800     75
18       P119           Marker Set   Stationery    400    120
19       P120           Coffee Mug  Accessories    350     90
20       P121               LED TV    Furniture  30000     12
21       P122              Printer  Electronics   8500     14
22       P123         Tablet Stand  Accessories    900     55
23       P124                Diary   Stationery    150    300
24       P125         External HDD  Electronics   6500     22

In [23]:
df.head()

  product_id         product_name     category  price  stock
0       P101       Wireless Mouse  Electronics   1200     50
1       P102  Mechanical Keyboard  Electronics   3500     30
2       P103         Laptop Stand  Accessories   1800     40
3       P104         Office Chair    Furniture   7000     15
4       P105         Water Bottle  Accessories    600    100

EDA (Exploratory Data Analysis)

In [24]:
df.head()

  product_id         product_name     category  price  stock
0       P101       Wireless Mouse  Electronics   1200     50
1       P102  Mechanical Keyboard  Electronics   3500     30
2       P103         Laptop Stand  Accessories   1800     40
3       P104         Office Chair    Furniture   7000     15
4       P105         Water Bottle  Accessories    600    100

In [25]:
df.tail()

   product_id  product_name     category  price  stock
20       P121        LED TV    Furniture  30000     12
21       P122       Printer  Electronics   8500     14
22       P123  Tablet Stand  Accessories    900     55
23       P124         Diary   Stationery    150    300
24       P125  External HDD  Electronics   6500     22

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    25 non-null     str
 1   product_name  25 non-null     str
 2   category      25 non-null     str
 3   price         25 non-null     int64
 4   stock         25 non-null     int64
dtypes: int64(2), str(3)
memory usage: 1.1 KB

In [27]:
df.describe()

              price       stock
count     25.000000   25.000000
mean    4841.200000   81.360000
std     6654.082281  110.712797
min       80.000000    8.000000
25%      600.000000   20.000000
50%     2200.000000   40.000000
75%     7000.000000   90.000000
max    30000.000000  500.000000

In [28]:
df.columns

Index(['product_id', 'product_name', 'category', 'price', 'stock'], dtype='str')

In [29]:
df.shape

(25, 5)