In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Iris.csv")

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: str

In [5]:
df = pd.read_csv("products.csv")

In [6]:
df['category']

0     Electronics
1     Electronics
2     Accessories
3       Furniture
4     Accessories
5     Electronics
6       Furniture
7     Electronics
8      Stationery
9      Stationery
10    Electronics
11      Furniture
12    Electronics
13    Accessories
14    Electronics
15    Electronics
16      Furniture
17    Electronics
18     Stationery
19    Accessories
20      Furniture
21    Electronics
22    Accessories
23     Stationery
24    Electronics
Name: category, dtype: str

In [21]:
df[["product_name","category","product_id"]]

           product_name     category product_id
0        Wireless Mouse  Electronics       P101
1   Mechanical Keyboard  Electronics       P102
2          Laptop Stand  Accessories       P103
3          Office Chair    Furniture       P104
4          Water Bottle  Accessories       P105
5       Monitor 24 inch  Electronics       P106
6           Study Table    Furniture       P107
7             USB Cable  Electronics       P108
8              Notebook   Stationery       P109
9               Pen Set   Stationery       P110
10    Bluetooth Speaker  Electronics       P111
11            Desk Lamp    Furniture       P112
12           Headphones  Electronics       P113
13             Backpack  Accessories       P114
14          Smart Watch  Electronics       P115
15               Webcam  Electronics       P116
16         Gaming Chair    Furniture       P117
17           Power Bank  Electronics       P118
18           Marker Set   Stationery       P119
19           Coffee Mug  Accessories       P120
20               LED TV    Furniture       P121
21              Printer  Electronics       P122
22         Tablet Stand  Accessories       P123
23                Diary   Stationery       P124
24         External HDD  Electronics       P125

In [8]:
df["product_name"]

0          Wireless Mouse
1     Mechanical Keyboard
2            Laptop Stand
3            Office Chair
4            Water Bottle
5         Monitor 24 inch
6             Study Table
7               USB Cable
8                Notebook
9                 Pen Set
10      Bluetooth Speaker
11              Desk Lamp
12             Headphones
13               Backpack
14            Smart Watch
15                 Webcam
16           Gaming Chair
17             Power Bank
18             Marker Set
19             Coffee Mug
20                 LED TV
21                Printer
22           Tablet Stand
23                  Diary
24           External HDD
Name: product_name, dtype: str

In [9]:
df["product_name"][20]

'LED TV'

In [10]:
type(df["product_name"][20])

str

In [11]:
df.loc[1]    #first row(by label) it may be 1,2,3 or a,b,c or anythig

product_id                     P102
product_name    Mechanical Keyboard
category                Electronics
price                          3500
stock                            30
Name: 1, dtype: object

In [12]:
df.iloc[1]      #first row (by position means by index)

product_id                     P102
product_name    Mechanical Keyboard
category                Electronics
price                          3500
stock                            30
Name: 1, dtype: object

In [13]:
df.head()

  product_id         product_name     category  price  stock
0       P101       Wireless Mouse  Electronics   1200     50
1       P102  Mechanical Keyboard  Electronics   3500     30
2       P103         Laptop Stand  Accessories   1800     40
3       P104         Office Chair    Furniture   7000     15
4       P105         Water Bottle  Accessories    600    100

In [14]:
df.loc[24,'price']

np.int64(6500)

In [15]:
df["price"][24]

np.int64(6500)

In [16]:
df.iloc[24,3]

np.int64(6500)

In [17]:
df.loc[0:2,["stock","price"]]     #slicing using loc   and last wali index inclusive milti hai yaha

   stock  price
0     50   1200
1     30   3500
2     40   1800

In [18]:
df.iloc[0:2,0:2]   #slicing using iloc and index is exclusive here

  product_id         product_name
0       P101       Wireless Mouse
1       P102  Mechanical Keyboard

In [19]:
df.at[0,"product_name"]    #accessing particular element by this

'Wireless Mouse'

In [20]:
df.iat[0,1]   #accessing particular element by this here we use index for that

'Wireless Mouse'

In [22]:
df.head()

  product_id         product_name     category  price  stock
0       P101       Wireless Mouse  Electronics   1200     50
1       P102  Mechanical Keyboard  Electronics   3500     30
2       P103         Laptop Stand  Accessories   1800     40
3       P104         Office Chair    Furniture   7000     15
4       P105         Water Bottle  Accessories    600    100

In [31]:
df[df['price']>3000 ]['product_name']  #filtering

1     Mechanical Keyboard
3            Office Chair
5         Monitor 24 inch
6             Study Table
10      Bluetooth Speaker
14            Smart Watch
16           Gaming Chair
20                 LED TV
21                Printer
24           External HDD
Name: product_name, dtype: str

In [33]:
df[df['price']>3000 ][['product_name','price','category']]  #filtering and getting two columns

           product_name  price     category
1   Mechanical Keyboard   3500  Electronics
3          Office Chair   7000    Furniture
5       Monitor 24 inch  12000  Electronics
6           Study Table   9500    Furniture
10    Bluetooth Speaker   4500  Electronics
14          Smart Watch   8000  Electronics
16         Gaming Chair  15000    Furniture
20               LED TV  30000    Furniture
21              Printer   8500  Electronics
24         External HDD   6500  Electronics

In [36]:
df[(df['price']>3000)&(df['category']=='Electronics')]  #filtering on two conditions

   product_id         product_name     category  price  stock
1        P102  Mechanical Keyboard  Electronics   3500     30
5        P106      Monitor 24 inch  Electronics  12000     20
10       P111    Bluetooth Speaker  Electronics   4500     25
14       P115          Smart Watch  Electronics   8000     18
21       P122              Printer  Electronics   8500     14
24       P125         External HDD  Electronics   6500     22

In [40]:
df.query("price<3000 and category == 'Furniture'")   #it returns copy not view

   product_id product_name   category  price  stock
11       P112    Desk Lamp  Furniture   2200     35