In [1]:
import pandas as pd

Handling Missing Data

In [7]:
df = pd.read_csv("data_cleaning_sample.csv")

In [8]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [9]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [10]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [11]:
df.dropna()   #provide non missing  and drop missing rows

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [12]:
df.dropna(axis = 1) #drop missing columns

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [13]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [15]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [17]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [18]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

Detecting and Removing Duplicate rows

In [20]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [21]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [22]:
df.duplicated(subset=["Name","Age"])   #checks for duplicate rows based only on the Name and Age columns.

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

String Operations with .str

In [23]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: str

In [24]:
df["City"].str.contains("delhi",case = False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [25]:
type(df["City"].str.contains("delhi",case = False))

pandas.Series

In [26]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [27]:
df["Email"].str.split("@")[0]

['alice', 'example.com']

In [28]:
type(df["Email"].str.split("@")[0])

list

Type Conversion

In [29]:
df2 = df.dropna().copy()

In [30]:
df2["Age"]=df2["Age"].astype(int)

In [31]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [35]:
df2["Join Date"] = pd.to_datetime(df2["Join Date"],dayfirst=True)

In [36]:
df2

    Name  Age         City Gender              Email  Join Date
0  Alice   25     New York      F  alice@example.com 2021-05-01
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15
4  David   22       Mumbai      M  david@example.com 2019-11-12
6  Alice   25     New York      F  alice@example.com 2021-05-01
7  Alice   25     New York      F  alice@example.com 2021-05-01

In [37]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [38]:
df2

    Name  Age         City Gender              Email  Join Date
0  Alice   25     New York      F  alice@example.com 2021-05-01
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15
4  David   22       Mumbai      M  david@example.com 2019-11-12
6  Alice   25     New York      F  alice@example.com 2021-05-01
7  Alice   25     New York      F  alice@example.com 2021-05-01

In [43]:
df2["Age Group"] = df2["Age"].apply(lambda x:"Adult" if x >= 25 else "Minor")

In [44]:
df2

    Name  Age         City Gender              Email  Join Date Age Group
0  Alice   25     New York      F  alice@example.com 2021-05-01     Adult
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai      M  david@example.com 2019-11-12     Minor
6  Alice   25     New York      F  alice@example.com 2021-05-01     Adult
7  Alice   25     New York      F  alice@example.com 2021-05-01     Adult

In [45]:
def isminor():
    return "Adult" if x >= 25 else "Minor"
    df2["Age Group"] = df2["Age"].apply(isminor)

In [46]:
df2

    Name  Age         City Gender              Email  Join Date Age Group
0  Alice   25     New York      F  alice@example.com 2021-05-01     Adult
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai      M  david@example.com 2019-11-12     Minor
6  Alice   25     New York      F  alice@example.com 2021-05-01     Adult
7  Alice   25     New York      F  alice@example.com 2021-05-01     Adult

In [47]:
gender_map = {"M":"Male","F":"Female","0":"Other"}
df["Gender"] = df["Gender"].map(gender_map)

In [48]:
df

      Name   Age         City  Gender              Email   Join Date
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021

In [49]:
# like map we use replace for particula not all