In [1]:
import pandas as pd

Soritng and Ranking

In [2]:
df = pd.read_csv("products.csv")

In [3]:
df

   product_id         product_name     category  price  stock
0        P101       Wireless Mouse  Electronics   1200     50
1        P102  Mechanical Keyboard  Electronics   3500     30
2        P103         Laptop Stand  Accessories   1800     40
3        P104         Office Chair    Furniture   7000     15
4        P105         Water Bottle  Accessories    600    100
5        P106      Monitor 24 inch  Electronics  12000     20
6        P107          Study Table    Furniture   9500     10
7        P108            USB Cable  Electronics    300    200
8        P109             Notebook   Stationery     80    500
9        P110              Pen Set   Stationery    250    150
10       P111    Bluetooth Speaker  Electronics   4500     25
11       P112            Desk Lamp    Furniture   2200     35
12       P113           Headphones  Electronics   2800     45
13       P114             Backpack  Accessories   1500     60
14       P115          Smart Watch  Electronics   8000     18
15       P116               Webcam  Electronics   2200     40
16       P117         Gaming Chair    Furniture  15000      8
17       P118           Power Bank  Electronics   1800     75
18       P119           Marker Set   Stationery    400    120
19       P120           Coffee Mug  Accessories    350     90
20       P121               LED TV    Furniture  30000     12
21       P122              Printer  Electronics   8500     14
22       P123         Tablet Stand  Accessories    900     55
23       P124                Diary   Stationery    150    300
24       P125         External HDD  Electronics   6500     22

In [5]:
df.sort_values("stock")

   product_id         product_name     category  price  stock
16       P117         Gaming Chair    Furniture  15000      8
6        P107          Study Table    Furniture   9500     10
20       P121               LED TV    Furniture  30000     12
21       P122              Printer  Electronics   8500     14
3        P104         Office Chair    Furniture   7000     15
14       P115          Smart Watch  Electronics   8000     18
5        P106      Monitor 24 inch  Electronics  12000     20
24       P125         External HDD  Electronics   6500     22
10       P111    Bluetooth Speaker  Electronics   4500     25
1        P102  Mechanical Keyboard  Electronics   3500     30
11       P112            Desk Lamp    Furniture   2200     35
2        P103         Laptop Stand  Accessories   1800     40
15       P116               Webcam  Electronics   2200     40
12       P113           Headphones  Electronics   2800     45
0        P101       Wireless Mouse  Electronics   1200     50
22       P123         Tablet Stand  Accessories    900     55
13       P114             Backpack  Accessories   1500     60
17       P118           Power Bank  Electronics   1800     75
19       P120           Coffee Mug  Accessories    350     90
4        P105         Water Bottle  Accessories    600    100
18       P119           Marker Set   Stationery    400    120
9        P110              Pen Set   Stationery    250    150
7        P108            USB Cable  Electronics    300    200
23       P124                Diary   Stationery    150    300
8        P109             Notebook   Stationery     80    500

In [6]:
df.sort_values("stock",ascending = False)

   product_id         product_name     category  price  stock
8        P109             Notebook   Stationery     80    500
23       P124                Diary   Stationery    150    300
7        P108            USB Cable  Electronics    300    200
9        P110              Pen Set   Stationery    250    150
18       P119           Marker Set   Stationery    400    120
4        P105         Water Bottle  Accessories    600    100
19       P120           Coffee Mug  Accessories    350     90
17       P118           Power Bank  Electronics   1800     75
13       P114             Backpack  Accessories   1500     60
22       P123         Tablet Stand  Accessories    900     55
0        P101       Wireless Mouse  Electronics   1200     50
12       P113           Headphones  Electronics   2800     45
15       P116               Webcam  Electronics   2200     40
2        P103         Laptop Stand  Accessories   1800     40
11       P112            Desk Lamp    Furniture   2200     35
1        P102  Mechanical Keyboard  Electronics   3500     30
10       P111    Bluetooth Speaker  Electronics   4500     25
24       P125         External HDD  Electronics   6500     22
5        P106      Monitor 24 inch  Electronics  12000     20
14       P115          Smart Watch  Electronics   8000     18
3        P104         Office Chair    Furniture   7000     15
21       P122              Printer  Electronics   8500     14
20       P121               LED TV    Furniture  30000     12
6        P107          Study Table    Furniture   9500     10
16       P117         Gaming Chair    Furniture  15000      8

In [8]:
df.sort_values(["stock","price"])   #if two stocks have same value then panda compare their price

   product_id         product_name     category  price  stock
8        P109             Notebook   Stationery     80    500
23       P124                Diary   Stationery    150    300
7        P108            USB Cable  Electronics    300    200
9        P110              Pen Set   Stationery    250    150
18       P119           Marker Set   Stationery    400    120
4        P105         Water Bottle  Accessories    600    100
19       P120           Coffee Mug  Accessories    350     90
17       P118           Power Bank  Electronics   1800     75
13       P114             Backpack  Accessories   1500     60
22       P123         Tablet Stand  Accessories    900     55
0        P101       Wireless Mouse  Electronics   1200     50
12       P113           Headphones  Electronics   2800     45
15       P116               Webcam  Electronics   2200     40
2        P103         Laptop Stand  Accessories   1800     40
11       P112            Desk Lamp    Furniture   2200     35
1        P102  Mechanical Keyboard  Electronics   3500     30
10       P111    Bluetooth Speaker  Electronics   4500     25
24       P125         External HDD  Electronics   6500     22
5        P106      Monitor 24 inch  Electronics  12000     20
14       P115          Smart Watch  Electronics   8000     18
3        P104         Office Chair    Furniture   7000     15
21       P122              Printer  Electronics   8500     14
20       P121               LED TV    Furniture  30000     12
6        P107          Study Table    Furniture   9500     10
16       P117         Gaming Chair    Furniture  15000      8

In [9]:
df2 = df.sort_values(["stock","price"]).copy()

In [10]:
df2

   product_id         product_name     category  price  stock
16       P117         Gaming Chair    Furniture  15000      8
6        P107          Study Table    Furniture   9500     10
20       P121               LED TV    Furniture  30000     12
21       P122              Printer  Electronics   8500     14
3        P104         Office Chair    Furniture   7000     15
14       P115          Smart Watch  Electronics   8000     18
5        P106      Monitor 24 inch  Electronics  12000     20
24       P125         External HDD  Electronics   6500     22
10       P111    Bluetooth Speaker  Electronics   4500     25
1        P102  Mechanical Keyboard  Electronics   3500     30
11       P112            Desk Lamp    Furniture   2200     35
2        P103         Laptop Stand  Accessories   1800     40
15       P116               Webcam  Electronics   2200     40
12       P113           Headphones  Electronics   2800     45
0        P101       Wireless Mouse  Electronics   1200     50
22       P123         Tablet Stand  Accessories    900     55
13       P114             Backpack  Accessories   1500     60
17       P118           Power Bank  Electronics   1800     75
19       P120           Coffee Mug  Accessories    350     90
4        P105         Water Bottle  Accessories    600    100
18       P119           Marker Set   Stationery    400    120
9        P110              Pen Set   Stationery    250    150
7        P108            USB Cable  Electronics    300    200
23       P124                Diary   Stationery    150    300
8        P109             Notebook   Stationery     80    500

In [11]:
df2.reset_index()

    index product_id         product_name     category  price  stock
0      16       P117         Gaming Chair    Furniture  15000      8
1       6       P107          Study Table    Furniture   9500     10
2      20       P121               LED TV    Furniture  30000     12
3      21       P122              Printer  Electronics   8500     14
4       3       P104         Office Chair    Furniture   7000     15
5      14       P115          Smart Watch  Electronics   8000     18
6       5       P106      Monitor 24 inch  Electronics  12000     20
7      24       P125         External HDD  Electronics   6500     22
8      10       P111    Bluetooth Speaker  Electronics   4500     25
9       1       P102  Mechanical Keyboard  Electronics   3500     30
10     11       P112            Desk Lamp    Furniture   2200     35
11      2       P103         Laptop Stand  Accessories   1800     40
12     15       P116               Webcam  Electronics   2200     40
13     12       P113           Headphones  Electronics   2800     45
14      0       P101       Wireless Mouse  Electronics   1200     50
15     22       P123         Tablet Stand  Accessories    900     55
16     13       P114             Backpack  Accessories   1500     60
17     17       P118           Power Bank  Electronics   1800     75
18     19       P120           Coffee Mug  Accessories    350     90
19      4       P105         Water Bottle  Accessories    600    100
20     18       P119           Marker Set   Stationery    400    120
21      9       P110              Pen Set   Stationery    250    150
22      7       P108            USB Cable  Electronics    300    200
23     23       P124                Diary   Stationery    150    300
24      8       P109             Notebook   Stationery     80    500

In [12]:
df2

   product_id         product_name     category  price  stock
16       P117         Gaming Chair    Furniture  15000      8
6        P107          Study Table    Furniture   9500     10
20       P121               LED TV    Furniture  30000     12
21       P122              Printer  Electronics   8500     14
3        P104         Office Chair    Furniture   7000     15
14       P115          Smart Watch  Electronics   8000     18
5        P106      Monitor 24 inch  Electronics  12000     20
24       P125         External HDD  Electronics   6500     22
10       P111    Bluetooth Speaker  Electronics   4500     25
1        P102  Mechanical Keyboard  Electronics   3500     30
11       P112            Desk Lamp    Furniture   2200     35
2        P103         Laptop Stand  Accessories   1800     40
15       P116               Webcam  Electronics   2200     40
12       P113           Headphones  Electronics   2800     45
0        P101       Wireless Mouse  Electronics   1200     50
22       P123         Tablet Stand  Accessories    900     55
13       P114             Backpack  Accessories   1500     60
17       P118           Power Bank  Electronics   1800     75
19       P120           Coffee Mug  Accessories    350     90
4        P105         Water Bottle  Accessories    600    100
18       P119           Marker Set   Stationery    400    120
9        P110              Pen Set   Stationery    250    150
7        P108            USB Cable  Electronics    300    200
23       P124                Diary   Stationery    150    300
8        P109             Notebook   Stationery     80    500

In [14]:
df2.reset_index(drop = True)  # new index column is dropped

   product_id         product_name     category  price  stock
0        P117         Gaming Chair    Furniture  15000      8
1        P107          Study Table    Furniture   9500     10
2        P121               LED TV    Furniture  30000     12
3        P122              Printer  Electronics   8500     14
4        P104         Office Chair    Furniture   7000     15
5        P115          Smart Watch  Electronics   8000     18
6        P106      Monitor 24 inch  Electronics  12000     20
7        P125         External HDD  Electronics   6500     22
8        P111    Bluetooth Speaker  Electronics   4500     25
9        P102  Mechanical Keyboard  Electronics   3500     30
10       P112            Desk Lamp    Furniture   2200     35
11       P103         Laptop Stand  Accessories   1800     40
12       P116               Webcam  Electronics   2200     40
13       P113           Headphones  Electronics   2800     45
14       P101       Wireless Mouse  Electronics   1200     50
15       P123         Tablet Stand  Accessories    900     55
16       P114             Backpack  Accessories   1500     60
17       P118           Power Bank  Electronics   1800     75
18       P120           Coffee Mug  Accessories    350     90
19       P105         Water Bottle  Accessories    600    100
20       P119           Marker Set   Stationery    400    120
21       P110              Pen Set   Stationery    250    150
22       P108            USB Cable  Electronics    300    200
23       P124                Diary   Stationery    150    300
24       P109             Notebook   Stationery     80    500

In [15]:
df2.reset_index(drop = True,inplace = True)

In [16]:
df2

   product_id         product_name     category  price  stock
0        P117         Gaming Chair    Furniture  15000      8
1        P107          Study Table    Furniture   9500     10
2        P121               LED TV    Furniture  30000     12
3        P122              Printer  Electronics   8500     14
4        P104         Office Chair    Furniture   7000     15
5        P115          Smart Watch  Electronics   8000     18
6        P106      Monitor 24 inch  Electronics  12000     20
7        P125         External HDD  Electronics   6500     22
8        P111    Bluetooth Speaker  Electronics   4500     25
9        P102  Mechanical Keyboard  Electronics   3500     30
10       P112            Desk Lamp    Furniture   2200     35
11       P103         Laptop Stand  Accessories   1800     40
12       P116               Webcam  Electronics   2200     40
13       P113           Headphones  Electronics   2800     45
14       P101       Wireless Mouse  Electronics   1200     50
15       P123         Tablet Stand  Accessories    900     55
16       P114             Backpack  Accessories   1500     60
17       P118           Power Bank  Electronics   1800     75
18       P120           Coffee Mug  Accessories    350     90
19       P105         Water Bottle  Accessories    600    100
20       P119           Marker Set   Stationery    400    120
21       P110              Pen Set   Stationery    250    150
22       P108            USB Cable  Electronics    300    200
23       P124                Diary   Stationery    150    300
24       P109             Notebook   Stationery     80    500

In [17]:
df2.sort_index()

   product_id         product_name     category  price  stock
0        P117         Gaming Chair    Furniture  15000      8
1        P107          Study Table    Furniture   9500     10
2        P121               LED TV    Furniture  30000     12
3        P122              Printer  Electronics   8500     14
4        P104         Office Chair    Furniture   7000     15
5        P115          Smart Watch  Electronics   8000     18
6        P106      Monitor 24 inch  Electronics  12000     20
7        P125         External HDD  Electronics   6500     22
8        P111    Bluetooth Speaker  Electronics   4500     25
9        P102  Mechanical Keyboard  Electronics   3500     30
10       P112            Desk Lamp    Furniture   2200     35
11       P103         Laptop Stand  Accessories   1800     40
12       P116               Webcam  Electronics   2200     40
13       P113           Headphones  Electronics   2800     45
14       P101       Wireless Mouse  Electronics   1200     50
15       P123         Tablet Stand  Accessories    900     55
16       P114             Backpack  Accessories   1500     60
17       P118           Power Bank  Electronics   1800     75
18       P120           Coffee Mug  Accessories    350     90
19       P105         Water Bottle  Accessories    600    100
20       P119           Marker Set   Stationery    400    120
21       P110              Pen Set   Stationery    250    150
22       P108            USB Cable  Electronics    300    200
23       P124                Diary   Stationery    150    300
24       P109             Notebook   Stationery     80    500

In [20]:
df2["Rank"] = df2["stock"].rank(ascending = False,method = "dense")  #dense is for equal value get same rank

In [21]:
df2

   product_id         product_name     category  price  stock  Rank
0        P117         Gaming Chair    Furniture  15000      8  24.0
1        P107          Study Table    Furniture   9500     10  23.0
2        P121               LED TV    Furniture  30000     12  22.0
3        P122              Printer  Electronics   8500     14  21.0
4        P104         Office Chair    Furniture   7000     15  20.0
5        P115          Smart Watch  Electronics   8000     18  19.0
6        P106      Monitor 24 inch  Electronics  12000     20  18.0
7        P125         External HDD  Electronics   6500     22  17.0
8        P111    Bluetooth Speaker  Electronics   4500     25  16.0
9        P102  Mechanical Keyboard  Electronics   3500     30  15.0
10       P112            Desk Lamp    Furniture   2200     35  14.0
11       P103         Laptop Stand  Accessories   1800     40  13.0
12       P116               Webcam  Electronics   2200     40  13.0
13       P113           Headphones  Electronics   2800     45  12.0
14       P101       Wireless Mouse  Electronics   1200     50  11.0
15       P123         Tablet Stand  Accessories    900     55  10.0
16       P114             Backpack  Accessories   1500     60   9.0
17       P118           Power Bank  Electronics   1800     75   8.0
18       P120           Coffee Mug  Accessories    350     90   7.0
19       P105         Water Bottle  Accessories    600    100   6.0
20       P119           Marker Set   Stationery    400    120   5.0
21       P110              Pen Set   Stationery    250    150   4.0
22       P108            USB Cable  Electronics    300    200   3.0
23       P124                Diary   Stationery    150    300   2.0
24       P109             Notebook   Stationery     80    500   1.0

In [22]:
df2.head()

  product_id  product_name     category  price  stock  Rank
0       P117  Gaming Chair    Furniture  15000      8  24.0
1       P107   Study Table    Furniture   9500     10  23.0
2       P121        LED TV    Furniture  30000     12  22.0
3       P122       Printer  Electronics   8500     14  21.0
4       P104  Office Chair    Furniture   7000     15  20.0

In [24]:
df = df[["product_name","category","price","stock","product_id"]]

In [25]:
df

           product_name     category  price  stock product_id
0        Wireless Mouse  Electronics   1200     50       P101
1   Mechanical Keyboard  Electronics   3500     30       P102
2          Laptop Stand  Accessories   1800     40       P103
3          Office Chair    Furniture   7000     15       P104
4          Water Bottle  Accessories    600    100       P105
5       Monitor 24 inch  Electronics  12000     20       P106
6           Study Table    Furniture   9500     10       P107
7             USB Cable  Electronics    300    200       P108
8              Notebook   Stationery     80    500       P109
9               Pen Set   Stationery    250    150       P110
10    Bluetooth Speaker  Electronics   4500     25       P111
11            Desk Lamp    Furniture   2200     35       P112
12           Headphones  Electronics   2800     45       P113
13             Backpack  Accessories   1500     60       P114
14          Smart Watch  Electronics   8000     18       P115
15               Webcam  Electronics   2200     40       P116
16         Gaming Chair    Furniture  15000      8       P117
17           Power Bank  Electronics   1800     75       P118
18           Marker Set   Stationery    400    120       P119
19           Coffee Mug  Accessories    350     90       P120
20               LED TV    Furniture  30000     12       P121
21              Printer  Electronics   8500     14       P122
22         Tablet Stand  Accessories    900     55       P123
23                Diary   Stationery    150    300       P124
24         External HDD  Electronics   6500     22       P125